// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzg1hUmJLXQqu3yBqodW0lkRaz5YuchVM',
    appId: '1:344615134676:android:9d35bfc2d9c60602652241',
    messagingSenderId: '344615134676',
    projectId: 'projet-dev-neskique',
    storageBucket: 'projet-dev-neskique.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLqVAimTnSiaK611SG3dFXJV-Yg3AoT8U',
    appId: '1:344615134676:ios:ce967f975a27f4b1652241',
    messagingSenderId: '344615134676',
    projectId: 'projet-dev-neskique',
    storageBucket: 'projet-dev-neskique.appspot.com',
    iosClientId: '344615134676-57llaok21bi8sj1hpnsklp4m18ampd5j.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
